.env.tpl
README.md

also add an example `.env.local` file as `.env.tpl`

chore: add documentation for running against a development service

---

src/app/page.tsx
src/app/space/create/page.tsx
src/components/Nav.tsx
src/components/Text.tsx
src/components/UploadsList.tsx

- better button group nav styles
- better space list styles
- add explainer to create space page
- better upload list styles
License: MIT

feat: nice button group, space list, and space create explainer

---

src/app/layout.tsx
src/app/space/[did]/layout.tsx
src/app/space/create/page.tsx
src/app/space/import/page.tsx
src/brand.tsx
src/components/SidebarLayout.tsx
src/components/SpaceCreator.tsx
src/components/SpaceFinder.tsx
src/share.tsx

- make navigating around console make sense by moving the logo back up top, and making it return you to the root of the app
- make the space finder work again
- fix small screen and desktop layouts
License: MIT

feat: fix SpaceFinder and improve nav

---

.github/workflows/deploy.yml

Motivation:
* https://github.com/web3-storage/console/issues/23
* I think this is happening because these env vars aren't set

ci: .github/workflows/deploy.yml preview job creates .env

---

README.md

Motivation:
* I need to test a whole release incl release-please and hope this creates a release-please pr

chore: add line to README to trigger/test a new release

---

.github/workflows/deploy.yml

The deployment url used in the environment is wrong. This fix that.
License: MIT

chore: fix prod env url to be console.web3.storage

---

src/components/PlanGate.tsx

feat: plan gate styles

---

src/app/space/layout.tsx
src/components/Nav.tsx
src/components/UsageBar.tsx

feat: usage bar

---

.github/workflows/deploy.yml

add stripe pricing table ID and publishable secret to deployed env

feat: add stripe pricing table config

---

pnpm-lock.yaml

Motivation:
* https://github.com/web3-storage/w3up/issues/1208

fix: update @web3-storage/upload-client to 12.3.2 to get new memory leak fixes

---

package.json
pnpm-lock.yaml

Fixes #87
See: https://github.com/cloudflare/next-on-pages/issues/656#issuecomment-1920295184
License: MIT

chore: pin `vercel` dep

---

pnpm-lock.yaml
src/app/plans/change/page.tsx
src/components/UsageBar.tsx
src/hooks.tsx

model it after https://web3.storage/pricing/
needs https://github.com/web3-storage/w3ui/pull/623 to work

fix: add "change plan" page

---

src/components/PlanGate.tsx

feat(copy): Add missing comma

---

package.json

So we're all on the same version (and package manager).

chore: Set `packageManager`

---

.github/workflows/deploy-storacha.yml

use up.storacha.network for service URL
update deploy scripts in github.

ci(github): Update deploy to use storacha.network

---

src/components/Authenticator.tsx
src/components/SidebarLayout.tsx

rather than the web3.storage docs

feat: update TOS links to point to the Storacha docs

---

.github/workflows/deploy-storacha.yml

fix: use the correct referral URL

---

src/app/settings/page.tsx
src/components/PlanGate.tsx

also add a way to hide the plan page after Stripe checkout to fix an annoying signup flow issue - will need to update Stripe to fully take advantage of this

fix: remove referrals feature flag

---

.github/workflows/deploy-storacha.yml
.github/workflows/deploy.yml
src/components/services.ts

- Using the correct gateway host
- https://github.com/storacha/project-tracking/issues/260

fix: using the correct gateway host

---

.github/workflows/deploy-storacha.yml
.github/workflows/deploy.yml

Updated the Prod Gateway Host to the new alias https://storacha.link

fix(prod): update gateway host
