- src/app/docs/page.tsx
- src/app/layout.tsx
- src/app/terms/page.tsx
- tailwind.config.ts
check all of `src/**` for tailwind classes
fixes: https://github.com/web3-storage/console/issues/6
License: MIT
> fix: tailwind to check entire src tree for clases

- package.json
- pnpm-lock.yaml
Motivation
* when I was trying to dev in this repo for first time, I was seeing hydration errors in react, plus warnings with `pnpm dev` that next wanted me to add `appDir: true` to my next.config.js. @travis helped me realize it was due to this
> fix: package.json uses next ^13.5.4 not latest

- .github/workflows/deploy.yml
Motivation
* https://github.com/web3-storage/console/issues/17
* make preview environments easier to find by having our github workflow files use the `environment` affordance to record when it deploys preview/staging environments to cloudflare pages. That way they will be browsable/clickable in the GitHub UI at https://github.com/web3-storage/console/deployments
note
> ci: .github/workflows/deploy.yml preview job sets gh environment

- .github/workflows/deploy.yml
Motivation:
* I'm sitting looking at this workflow waiting for release after merging a release-please pr and I don't need/want to have to wait for `preview` here https://github.com/web3-storage/console/actions/runs/6778644273 . This was already deployed to a preview environment went it hit `main` branch the first time, which triggered the release-please PR, and now this is the second run on `main` so I don't wanna have to wait for a second `preview` job
> ci: .github/workflows/deploy.yml release job does not wait on preview

- src/components/Authenticator.tsx
Original change didn't remove a variable and resultant text needed to be centred.
> docs: update ToS reference

- .env.tpl
I think developers should default to using staging, since with the addition of plan gating on the client and server they will otherwise need to enter real credit card information to do basic development. In staging they'll still need to go through the checkout flow, but can use fake credit card information (ie 4242 4242 4242 4242 and others listed at https://stripe.com/docs/testing?testing-method=card-numbers)
I've also updated to the "test mode" Stripe pricing table that redirects to localhost:3000 - the previously specified pricing table redirects to staging after checkout is complete
> chore: update `.env.tpl` to sensible defaults for local dev

- src/components/Authenticator.tsx
- src/components/Loader.tsx
- src/components/PlanGate.tsx
- src/components/UsageBar.tsx
- src/hooks.tsx
We fetch `plan/get` wayyy too much and it leads to janky loaders when navigating between sections that use different instances of the same layout component, like the space list and the import/create tabs.
Using SWR fixes this by utilizing the "stale while revalidate" pattern to served a cached version of the `plan/get` result in all cases - no more weird loader jitters!
Also DRY up the top level loaders so they don't flash black-and-centered and then white-and-left-justified.
> feat: extract usePlan and use it to chill our plan/get game

- package.json
- pnpm-lock.yaml
- src/app/logout/page.tsx
This will work once https://github.com/web3-storage/w3ui/pull/595 is released.
> fix: get logout page working again

- src/components/SpaceCreator.tsx
We were not doing this, and as a result any spaces created in the web console recently will not be recoverable.
I'd like to get this bugfix into production ASAP but have left TODOs for follow-on work that should be completed as soon as possible.
We should also give users the ability to see if their space is recoverable from the service. I'll create issues for all of this.
> fix: delegate space recovery after creation

- src/share.tsx
> fix: do not allow navigate without download URL being set

- package.json
- pnpm-lock.yaml
- src/components/Uploader.tsx
Use the new w3ui Uploader's directory upload support to allow users to upload directories. Also allow them to wrap a single file in a directory.
I've moved this to a radio group because we are going to add the ability to upload a CAR file, which will be a third option and will use a different upload function.
> feat: directory uploads

- src/components/Uploader.tsx
Use new CAR upload support in w3ui to allow users to upload raw CAR files.
> feat: support CAR uploads

- .env.tpl
- .github/workflows/deploy.yml
- src/components/UsageBar.tsx
This will allow customers to change their billing details. Might be worth rethinking where this link goes, but @heyjay44 and I think this makes sense for now.
> feat: add a link to the customer self-service billing portal

- src/app/space/[did]/page.tsx
- src/app/space/[did]/root/[cid]/page.tsx
- src/cache.ts
Adds a remove button and confirmation modal to make sure folks _really_ want to remove the upload.
resolves https://github.com/web3-storage/w3up/issues/1298
> feat: remove upload

- package.json
- pnpm-lock.yaml
- src/app/layout.tsx
- src/app/plans/change/page.tsx
- src/components/Toaster.tsx
- src/hooks.tsx
- src/toaster.ts
Use `react-hot-toast` to introduce "toaster" style notifications:
https://react-hot-toast.com/
These should be refined over time, but as an experiment I've introduced this on the "plan change" page and am using it to let the user know when something goes wrong:
https://github.com/web3-storage/console/assets/1113/ffe3c1cf-5a42-4471-920c-649bfecb36a4
or when something goes right:
https://github.com/web3-storage/console/assets/1113/af7f5bd2-cf20-482c-803c-22d5804ed86a
If this seems like a good pattern to everyone I think we should start using it more broadly - no longer will our users be forced to watch a whole file upload just to get feedback about its success or failure!
> feat: add a toaster for notifications and other snacks

- .github/workflows/deploy.yml
- src/components/services.ts
Triggered a release to make sure the repo was migrated successfully.
- added a missing write perm to [GitHub - marocchino/sticky-pull-request-comment: create comment on pull request, if exists update that comment.](https://github.com/marocchino/sticky-pull-request-comment), as it seems those changes [can be set org-wide](https://github.com/organizations/w3s-project/settings/actions) but it's best to be explicit
- more info in [Got error of \`Resource not accessible by integration\` where re-creating the same name repo · community · Discussion #60820 · GitHub](https://github.com/orgs/community/discussions/60820#discussioncomment-6445895).
> chore: migrate repo

- .github/workflows/deploy.yml
Making Github actions permissions explicit as we migrate between orgs.
> fix: allow release-please to release

- src/app/plans/change/page.tsx
My fix for the linter's dissatisfaction resulted in an escaped `<br/>` tag - fix that
> fix: don't render escaped <br/>

- .env.tpl
- README.md
- src/components/SpaceCreator.tsx
If the `NEXT_PUBLIC_W3UP_PROVIDER` environment variable is not set, the app will use `did:web:web3.storage` as the default storage provider. That works well if we are pointing to  Prod environment (https://up.web3.storage), however, if we use the Staging environment (https://staging.up.web3.storage) it will fail to provision the space because the default provider is invalid for Staging.
- Verify if the Space Provisioning result contains an error. If so, throw the error to prevent the user from continuing the flow and attempting to upload files.
- Updated Docs and sample Env Vars.
> fix(space-creator): check provision result before proceeding

- .github/workflows/deploy.yml
I've updated the workflow to use the `old-main` branch to deploy the `https://console.web3.network` app.
> fix: deploy.yml needs to use the old-main branch

- .github/workflows/deploy-storacha.yml
I've fixed the `deploy-storacha.yml` workflow to build previews and changelogs, run tests, and create releases using the same conditionals we had while deploying to `https://console.web3.storage`.
> fix: deploy-storacha.yml needs to use the new main branch

- src/components/SpaceCreator.tsx
- src/share.tsx
Fixes: https://github.com/storacha/console/issues/94
When you import an Space from the UCAN file it generates several components as Space Preview:
Ideally, it would render only one component for the Space that was imported:
This PR fixes that component and includes the information icon to show the capabilities delegated to that shared Space.
> fix: import space preview

- package.json
- pnpm-lock.yaml
- src/app/space/[did]/root/[cid]/shard/[shard]/page.tsx
Reopens https://github.com/storacha/console/pull/118 against `main`, and should address @alanshaw's [feedback](https://github.com/storacha/console/pull/118#pullrequestreview-2279593433) (making the Shard page work again).
> feat: Use Blob protocol

- .env.tpl
- .github/workflows/deploy-storacha.yml
- .github/workflows/deploy.yml
- README.md
- src/components/W3UIProvider.tsx
- src/components/services.ts
This PR adds a `receiptsEndpoint` configuration to `W3UIProvider`. The receipts URL is currently not provided by the console to the client as an option, so this ensures the endpoint is explicitly configured.
Uploading in staging is currently broken. The console shows an error when attempting to retrieve the receipt.
The receipts endpoint being used for staging is incorrect due to a missing configuration. This causes the value to default to a hardcoded production endpoint.
> fix: add missing receiptsEndpoint to W3UIProvider

- src/components/PlanGate.tsx
we really don't want to show the plan gate if we just finished Stripe checkout - sometimes Stripe isn't fast enough with the webhook so this will help us provide a UX that makes sense even in this case
> fix: make it possible to skip the plan gate after Stripe checkout

- src/components/PlanGate.tsx
it turns out Stripe already adds the `checkout.session` query param to this URL - this means we don't even need to update Stripe to fix this!
> fix: tweak plan gate query param

- .env.tpl
- .github/workflows/deploy-storacha.yml
- .gitignore
- next.config.js
- package.json
- pnpm-lock.yaml
- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
- src/app/api/sentry-example-api/route.ts
- src/app/global-error.tsx
- src/app/sentry-example-page/page.tsx
- src/instrumentation.ts
We need to track down some persistent errors in the app, and should have better visibility in general into web client performance - this will help with both.
Staging/prod configuration are included in the build script here, and I've configured separate projects for dev/staging/prod in Sentry.
Much of this was autogenerated by the Sentry Next.js setup wizard.
> feat: add Sentry error tracking

- .github/workflows/deploy-storacha.yml
- next.config.js
this will give us nice stack traces and other conveniences in Sentry
> fix: add sentry auth token to enable sourcemap upload

- package.json
- pnpm-lock.yaml
It updates the `w3ui-react` library to the latest version, which includes the updated `w3up-client` package. This enables the creation of spaces that authorize the Storacha Gateway to serve upload content.
> fix: create space using the latest w3up-client version

- package.json
- pnpm-lock.yaml
Update the `w3ui-react` lib to the latest version, so we can use the `w3up-client` fix that saves the new space to grant access to the agent.
> fix: create space

- .env.tpl
- .github/workflows/deploy-storacha.yml
- .github/workflows/deploy.yml
- src/components/SpaceCreator.tsx
In order to create new spaces in `Staging` or `localhost` environments we need to configure the w3up-client to authorize the correct gateway service, otherwise, it will default to the Production Storacha Gateway.
This PR implements the logic to create the gateway connection based on the environment variables and passes that connection to the `w3up-client.createSpace` call, so the correct service is authorized.
> fix: gateway authorization based on env

- src/share.tsx
Resolves: https://github.com/storacha/project-tracking/issues/238
The client provides a new method to share a Space via delegation, so we don't need to implement that on the Console App side, we just need to call the new method.
> refactor: using the new client method for space sharing

- .env.tpl
- .github/workflows/deploy-storacha.yml
- .github/workflows/deploy.yml
- src/app/space/[did]/root/[cid]/page.tsx
- src/components/SpaceCreator.tsx
- src/components/Uploader.tsx
- src/components/services.ts
- src/lib/migrations/nft-storage.ts
- src/lib/migrations/web3-storage.ts
- When creating a space, the system will use an environment variable to determine which Gateway is authorized to serve its content. If the environment variable is not defined, the Storacha Production Gateway will be authorized by default.
- If the Staging Gateway is specified, IPFS links must point to `ipfs-staging.w3s.link` instead of `ipfs.w3s.link`. Otherwise, requests will bypass the correct service, preventing proper validation of the content authorization flow.
- Refactored the code to dynamically read the IPFS Gateway URL from the environment variable and construct the appropriate URL for content retrieval.
- Updated deployment configuration files to include the new environment variable for Gateway selection.
- Resolved a minor compilation issue in `nft-storage.ts` and …
> fix: set ipfs gateway url based on env var

- .github/workflows/deploy-storacha.yml
- .github/workflows/deploy.yml
- src/components/services.ts
- Error while creating a new space in production:
> create:1 Access to fetch at 'https://w3s.link/' from origin 'https://console.storacha.network' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
- I was using the `w3s.link` as the gateway host to be authorized to serve the space content, but the cors policy defined in the `w3s.link` doesn't allow redirects for a preflight request. 
- It doesn't happen in staging because in staging I am using the actual gateway, and not the proxy: `freeway-staging.dag.haus`.
- Authorize the actual production gateway instead of the proxy: `https://freeway.dag.haus`.
> fix: cors preflight issue in production

- src/app/space/create/page.tsx
nitpick [non-blocking]:
Add an a.
A space is [a] decentralized bucket.
See image for original.
> fix: typo on space page
